-- ============================================================
-- SEED: Pedidos (DESCONTINUADO)
-- Projeto: SistemaCompleto - rotaperfumes-api
-- Data: 2026-09-13
-- Agente: DataBrain (🌸)
--
-- Este arquivo continha dados fictícios de pedidos e foi esvaziado.
-- Os dados reais de pedidos e itens_pedido são importados a partir dos
-- CSVs de origem (dados/erp/pedidos.csv e dados/erp/itens_pedido.csv)
-- via comando Go dedicado, seguindo o mesmo padrão de importclientes e
-- importprodutos (upsert idempotente, sem dados inventados):
--
--   make db-import-pedidos
--
-- Ver: apis/shared/cmd/importpedidos/main.go
-- ============================================================
